**Numpy**
- NumPy is a core Python library for scientific computing.
- Fast and efficient numerical operations.
- Provides support for:
  - Mathematical and logical operations
  - Sorting and selecting data
  - Shape manipulation
  - Linear algebra
  - Statistical operations
  - Random number simulation
  - Fourier transforms and I/O operations
- NumPy operations are optimized for performance compared to pure Python.



**Core object : ```ndarray```**
- It stores data in a contiguous block of memory.
- All elements in an ndarray are of the same (homogeneous) data type.
- Supports multi-dimensional data (1D, 2D, 3D, …).

**Numpy Array VS Python Sequences (Lists)**
| Aspect | NumPy Array | Python List (Sequence) |
|------|------------|------------------------|
| Size | Fixed size at creation | Dynamic size (can grow or shrink) |
| Memory Allocation | Stored in contiguous memory | Stored as references to objects |
| Data Type | Homogeneous (same data type) | Heterogeneous (mixed data types allowed) |
| Resizing | Creates a new array and deletes the old one | Resized in place |
| Performance | Faster for numerical computations | Slower for large numerical operations |
| Memory Efficiency | More memory efficient | Less memory efficient |
| Dimensionality | Supports multi-dimensional arrays (n-D) | Primarily one-dimensional |
| Use in Scientific Libraries | Widely used and often required | Usually converted to NumPy arrays internally |
| Code Complexity | Less code for complex operations | More code for numerical tasks |


### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.56075727, 0.5392108 , 0.54193959, 0.99860338],
       [0.94935265, 0.5066194 , 0.6548394 , 0.88986112],
       [0.06305414, 0.12061161, 0.63705249, 0.63046018]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[12., 22., 46.],
       [ 1., 98., 32.],
       [58., 87., 56.]])

In [ ]:
np.max(a1)

np.float64(98.0)

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 1944., 26772.,  1802.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([113.55555556, 176.22222222, 660.66666667])

In [ ]:
m = np.array([[1, 2], [3, 4]])
np.mean(m, axis=0)   # column-wise
np.mean(m, axis=1)   # row-wise

In [ ]:
a = np.array([1, 2, np.nan, 4])

np.isnan(a)
np.nanmean(a)

np.float64(2.3333333333333335)

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.95637593, -0.53657292,  0.84147098],
       [ 0.90929743, -0.8462204 ,  0.52908269],
       [-0.99177885,  0.37960774,  0.39592515]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[5.32048241e+11, 1.62754791e+05, 2.71828183e+00],
       [7.38905610e+00, 9.74480345e+09, 5.83461743e+14],
       [4.31123155e+15, 1.33833472e+42, 1.04137594e+23]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[34., 62., 69.],
       [36., 19., 38.]])

In [ ]:
a = np.array([1, 1, 2, 3, 3])

np.unique(a)
np.unique(a, return_counts=True)


array([1, 2, 3])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Boolean indexing

In [ ]:
a = np.array([10, 20, 30, 40])

a[a > 25]


array([30, 40])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

- Provides efficient n-dimensional arrays (ndarray) for storing data.

- Enables fast numerical computation using vectorization.

- Used for data preprocessing like scaling, normalization, and transformations.

- Supports statistical operations (mean, variance, std, etc.) for EDA.

- Helps in filtering and slicing data using boolean indexing.

- Provides linear algebra operations required in machine learning.

- Used for random sampling and simulations in ML models.

- Memory-efficient compared to Python lists.

- Acts as the foundation for libraries like Pandas, Scikit-learn, TensorFlow.